### ISSUE TITLE
Rename nix-build-status to nix-bisect-status

### ISSUE THREAD

**Issue by veprbl** [timokau/nix-bisect#8]
When searching the shell history, "nix-build-status" will appear in the search for "nix-build". "nix-bisect-status" should allow to better distinguish those two commands.

**Comment by timokau** [comment]
Renaming it to `nix-bisect-status` would suggest that it queries the current status of the bisect run. That's not the case. Its also not particularly specific to bisection, it can be used any time you want to know the status of a build (without necessarily building it). The only bisect-specific thing are the default return codes.

Why is it a problem that it will appear in `nix-build` searches?

**Comment by veprbl** [comment]
> Renaming it to nix-bisect-status would suggest that it queries the current status of the bisect run.

"nix-bisect-build-status" then? "nix-bisect-build"?

> Its also not particularly specific to bisection

In another words: it's somewhat specific, like code 125 meaning skip (which is understood by both git bisect and hg bisect).

> Why is it a problem that it will appear in nix-build searches?

Matter of convenience to me. I have my shell setup to search history by prefix on up-down keys. If I want to rebuild something again I type "nix-b" and up. Getting "nix-build-status --help" as the first result was what made me open this issue.

It also makes sense that the nix-bisect provides a utility called nix-bisect.

**Comment by timokau** [comment]
> > Renaming it to nix-bisect-status would suggest that it queries the current status of the bisect run.
> 
> "nix-bisect-build-status" then? "nix-bisect-build"?

The first one is a bit of a mouthful, the second one is better but doesn't convey the "this may not actually build the package" bit.

> > Its also not particularly specific to bisection
> 
> In another words: it's somewhat specific, like code 125 meaning skip (which is understood by both git bisect and hg bisect).

Yes its optimized for use in bisection, but that isn't the only use. You can specify custom exit codes or use it interactively.

> > Why is it a problem that it will appear in nix-build searches?
> 
> Matter of convenience to me. I have my shell setup to search history by prefix on up-down keys. If I want to rebuild something again I type "nix-b" and up. Getting "nix-build-status --help" as the first result was what made me open this issue.

I see your point, but I don't think thats enough reason to replace the name by a less accurate one. Any other nix build will have the same effect of pushing other builds further down the history. Fuzzy search helps with this for example.

> It also makes sense that the nix-bisect provides a utility called nix-bisect.

That is true. The name of the project is mostly a historical artefact now. In earlier versions there was a single `nix-bisect` binary that did everyghing from building the package to running the bisection. That is no longer the case. I already considered splitting it up at some point. The bisect runner and `bisect-env` are useful independent of nix, `nix-build-status` is useful independent of bisection.

**Comment by veprbl** [comment]
> "this may not actually build the package"

In our pure world packages are not considered built unless you return a store path or make a gc root :)

> Yes its optimized for use in bisection, but that isn't the only use. You can specify custom exit codes or use it interactively.

I think naming would be the last thing to stand in the way of witty nix users who (hypothetically) may want to repurpose nix-bisect for something else.

Seems like you've thought about this quite a bit, @timokau, and, maybe, current name makes more sense. Thank you for considering the rename. Let's close this for now.

**Comment by timokau** [comment]
> > "this may not actually build the package"
> 
> In our pure world packages are not considered built unless you return a store path or make a gc root :)

Exactly my point, `nix-build-status` doesn't do that. It only figures out the status of the build, querying caches if possible and performing the build if needed. It then prints the status and exits with a configurable exit code.

> > Yes its optimized for use in bisection, but that isn't the only use. You can specify custom exit codes or use it interactively.
> 
> I think naming would be the last thing to stand in the way of witty nix users who (hypothetically) may want to repurpose nix-bisect for something else.

True, I just don't think the proposed alternatives are an improvement over the current name.

> Seems like you've thought about this quite a bit, @timokau, and, maybe, current name makes more sense. Thank you for considering the rename. Let's close this for now.

Alright :) Maybe I or somebody else will come up with a better name in the future, or maybe the functionality will shift a bit and make a different name more sensible. Still early days :)

Thank you for the proposal!
