### ISSUE TITLE
How do I utilise the system.py example ?

### ISSUE THREAD

**Issue by 573** [timokau/nix-bisect#9]
Tried
```
python3 doc/examples/system.py
```
with nix-bisect installed getting
> Traceback (most recent call last):
  File "doc/examples/system.py", line 11, in <module>
    from nix_bisect import nix, test_util, git_bisect
ModuleNotFoundError: No module named 'nix_bisect'

**Comment by timokau** [comment]
You need to make sure `python3` knows how to find the `nix-bisect` library. Unfortunately `default.nix` will only put the CLI into `PATH`. I'm not sure if there is a better way to do this. For my personal setup I currently use a snippet like this one in my home-manager configuration:

```nix
home.packages = let
  nix-bisect = pkgs.python3.pkgs.buildPythonPackage rec {
    pname = "nix-bisect";
    src = pkgs.fetchFromGitHub {
      owner = "timokau";
      repo = "nix-bisect";
      rev = "REV_TO_INSTALL";
      sha256 = "0000000000000000000000000000000000000000000000000000";
    };
  };
in with pkgs; [
  (python3.withPackages (pkgs: with pkgs; [
    nix-bisect # bisect nix packages
    # other python packages...
  ]))
  # more packages
]
```

I currently

**Comment by 573** [comment]
I am getting

> building '/nix/store/imbf8vqqqb0wqgzgjpyy91n9krl5r9cn-home-manager-path.drv'...
collision between `/nix/store/3nlpb5hivhi8fvmj49lbq7js7vyfmzlr-python3-3.7.5-env/bin/2to3' and `/nix/store/p0m8ygm3ndz5x00f2dv8c9pygr3vz9r1-python3-3.7.5-env/bin/2to3'
killing process 1627: No such process
note: keeping build directory '/tmp/nix-build-home-manager-path.drv-2'
builder for '/nix/store/imbf8vqqqb0wqgzgjpyy91n9krl5r9cn-home-manager-path.drv' failed with exit code 255
cannot build derivation '/nix/store/axv1z1spjhjnlcrg1lb3xsvx9w0pkr8f-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/axv1z1spjhjnlcrg1lb3xsvx9w0pkr8f-home-manager-generation.drv' failed
with that.

Strangely when doing a similar thing with

```
# usage: nix-shell ~/.config/nixpkgs/program/nix-bisect/default.nix
{}:
with import <nixpkgs>{};
let
  inherit (pkgs) python3Packages;
  inherit (pkgs) fetchFromGitHub;
  inherit (python3Packages) buildPythonPackage;
nix-bisect = buildPythonPackage rec {
  pname = "nix-bisect";
  version = "0.4.1";
  src = fetchFromGitHub {
    owner = "timokau";
    repo = "nix-bisect";
    rev = "v${version}";
    sha256 = "1z5j7qjzsxq7i9kklvwn8dv327zrs21k1nwwif54lslck7gy6nyk";
  };
  propagatedBuildInputs = with python3Packages; [
    appdirs pexpect numpy
  ];

  doCheck = false;
};
in
  mkShell
  {
  name = "nix-bisect-env";
  buildInputs = with python3Packages; [ nix-bisect ];
  shellHook = ''
    echo "Whatever makes this happen."
    '';
  dontFixup = true;
}
```

I can then `python3 system.py` but yes having this hm-managed would be fine. IDK looks like hm issue, doesn't it ?

**Comment by timokau** [comment]
That sounds like you added two different python environments to your home configuration and the two envs provide the same binaries.

**Comment by 573** [comment]
@timokau you're right, see [tracking ticket](https://github.com/rycee/home-manager/issues/1183)
